spring:
  ###### redis 配置
  redis:
    host: 192.168.194.129
    database: 0
    port: 6379
    password: 123
    # 连接超时时间 （默认1天）
    timeout: 36000s
    jedis:
      pool:
        # 连接池最大连接数 默认 8（-1 ：表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间 默认-1ms （-1 :表示没有限制） 这里设置1分钟
        max-wait: 60000ms
        # 最大空闲连接  默认 8
        max-idle: 8